language: go
go:
  - tip

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/ | grep -v /packages/)
  - go get github.com/golang/lint/golint

script:
  - go get -d -v ./...
  - go install github.com/aki237/ligo/cmd/ligo/
  - test -z $(gofmt -s -l $GO_FILES)
  - go test -v -race ./...
  - go vet ./...
  - golint -set_exit_status $(go list ./...)
