language: go
go:
  - tip

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/ | grep -v /packages/)
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/megacheck

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - go test -v -race ./...
  - go vet ./...
  - megacheck ./...
  - golint -set_exit_status $(go list ./...)
  - go install $GOPATH/src/github.com/aki237/ligo/cmd/ligo/
